# Generated by Django 5.0.3 on 2024-03-08 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0002_offer_unit_delete_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('pricing_time_from', models.DateField(blank=True, null=True)),
                ('pricing_time_to', models.DateField(blank=True, null=True)),
                ('pricing_notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_from', models.DateTimeField()),
                ('reservation_to', models.DateTimeField(blank=True, null=True)),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_by_manager', models.CharField(blank=True, choices=[('A', 'Confirmed'), ('N', 'Not Confirmed')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('MANAGER', 'Manager'), ('USER', 'User')], default='USER', max_length=8)),
            ],
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='offer',
            new_name='belongs_to_offer',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='capacity',
            new_name='count_of_units',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='to_date',
        ),
        migrations.AddField(
            model_name='offer',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='manager_of_this_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='additional_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='max_simultneous_reservations',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pricing'),
        ),
    ]
