# Generated by Django 5.0.3 on 2024-03-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_unit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='additional_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
