# Generated by Django 5.0.3 on 2024-03-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_delete_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='max_count_of_categories',
            new_name='max_count_of_units',
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=10)),
                ('belongs_to_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
        ),
    ]
