# Generated by Django 5.0.3 on 2024-03-12 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_max_count_of_categories_category_max_count_of_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_slots', to='base.unit')),
            ],
        ),
    ]
