# Generated by Django 5.0.3 on 2024-03-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_reservationslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
