# Generated by Django 5.0.3 on 2024-03-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_unit_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('unit_name', 'belongs_to_category')},
        ),
    ]
