# Generated by Django 5.0.3 on 2024-03-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_reservation_belongs_to_offer_reservation_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='belongs_to_offer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_category',
        ),
    ]
