# Generated by Django 5.0.3 on 2024-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_reservation_belongs_to_offer_reservation_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_email',
            field=models.CharField(default='email', max_length=20),
        ),
    ]
