# Generated by Django 5.0.3 on 2024-03-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_reservation_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='max_count_of_units',
            new_name='count_of_units',
        ),
    ]
