# Generated by Django 5.0.3 on 2024-03-13 07:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_max_count_of_units_category_count_of_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_from']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='belongs_to_offer',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='The current status of the reservation', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='belongs_to_category',
            field=models.ForeignKey(help_text='The category of the unit being reserved', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='base.category'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmed_by_manager',
            field=models.CharField(blank=True, choices=[('A', 'Confirmed'), ('N', 'Not Confirmed')], help_text='Whether the reservation is confirmed by a manager', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_email',
            field=models.CharField(default='email@example.com', help_text='Customer email for reservation communication', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_from',
            field=models.DateTimeField(help_text='Start time/date of the reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_to',
            field=models.DateTimeField(blank=True, help_text='End time/date of the reservation', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the reservation was submitted'),
        ),
    ]
