# Generated by Django 5.0.3 on 2024-03-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['submission_time']},
        ),
    ]
