# Generated by Django 5.0.3 on 2024-03-14 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_reservation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationslot',
            name='end_time',
        ),
        migrations.AddField(
            model_name='reservationslot',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
