# Generated by Django 5.0.3 on 2024-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_reservationslot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(default='Jan Novák', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='verification_token',
            field=models.CharField(default=1234, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
