# Generated by Django 5.0.3 on 2024-03-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_reservation_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-submission_time']},
        ),
    ]
