# Generated by Django 5.0.3 on 2024-03-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
    ]
