# Generated by Django 5.0.3 on 2024-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_unit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationslot',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
