# Generated by Django 5.0.3 on 2024-03-28 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_reservationslot_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationslot',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
