# Generated by Django 5.0.3 on 2024-03-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_reservationslot_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationslot',
            unique_together={('unit', 'start_time')},
        ),
    ]
