# Generated by Django 5.0.3 on 2024-03-29 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_reservationslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='closing_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='opening_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
