# Generated by Django 5.0.3 on 2024-03-29 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_category_closing_time_category_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='closing_time',
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='category',
            name='opening_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
