# Generated by Django 5.0.3 on 2024-04-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_offer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unit_names',
            field=models.JSONField(default=list),
        ),
    ]
