# Generated by Django 5.0.3 on 2024-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_category_unit_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_capacity',
            field=models.IntegerField(default=1, help_text='How many reservations at one time are possible? e.g.seminar = 20 or parkplace = 1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='count_of_units',
            field=models.IntegerField(default=1, help_text='How many units are there in this category? e.g. 5 parkplaces for disabled people'),
        ),
        migrations.AlterField(
            model_name='reservationslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('closed', 'Closed')], max_length=20),
        ),
    ]
