# Generated by Django 5.0.3 on 2024-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_reservationslot_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('closed', 'Closed')], max_length=20),
        ),
    ]
