# Generated by Django 5.0.3 on 2024-04-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_reservationslot_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
