# Generated by Django 5.0.3 on 2024-04-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='additional_time',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
    ]
