# Generated by Django 5.0.3 on 2024-04-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_category_additional_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='max_simultneous_reservations',
            new_name='max_simultaneous_reservations',
        ),
    ]
