# Generated by Django 5.0.3 on 2024-04-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_managerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='manager_link',
            field=models.URLField(blank=True),
        ),
    ]
