# Generated by Django 5.0.3 on 2024-04-24 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_category_additional_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='closing_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AlterField(
            model_name='category',
            name='opening_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
