# Generated by Django 5.0.3 on 2024-04-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_managerprofile_optimization_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='optimization_strategy',
            field=models.CharField(choices=[('min_units', 'Minimal units usage'), ('equally_distributed', 'Equally distributed reservations'), ('no_optimization', 'No optimizaton')], default='min_units', max_length=30),
        ),
    ]
